#ifndef EGL_EGLEXT_H
#define EGL_EGLEXT_H
#include "egl.h"
typedef void *EGLImageKHR;
#define EGL_NO_IMAGE_KHR ((EGLImageKHR)0)
#define EGL_IMAGE_PRESERVED_KHR 0x30D2
#define EGL_NATIVE_BUFFER_ANDROID 0x3140
#define EGL_SYNC_FENCE_KHR 0x30F9
#define EGL_SYNC_NATIVE_FENCE_ANDROID 0x3144
#define EGL_SYNC_NATIVE_FENCE_FD_ANDROID 0x3145
#endif
